version: '3.9'

services:
  burger:
    container_name: burger
    image: cr.yandex/${ID_REGISTRY}/burger:${TAG}
    restart: always
    environment:
      API_URI: ${API_URI}
      WS_URI: ${WS_URI}
      NODE_ENV: production
    depends_on:
      nginxproxymanager:
        condition: service_started
  nginxproxymanager:
    container_name: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxdata:/data
      - ./letsencrypt:/etc/letsencrypt
volumes:
  nginxdata:
